### PR TITLE
Fix potential file descriptor leak

### PR DESCRIPTION
**Pull request by zhao-kun**

### CODE REVIEW

**Comment by grgalex** [comment]
@zhao-kun

Good catch! Thanks for the PR!

I'll take a look when I have some time.

**Comment by grgalex** [comment]
@zhao-kun 

I usually prefer to include `Signed-off-by` and `Reviewed-by` comments at the end of the commit.

Therefore, I suggest we change the commit message to:
```
client: Fix potential file descriptor leak

Signed-off-by: Kun Zhao <zhaokun.km@gmail.com>
Reviewed-by: George Alexopoulos <giorgosalexo0@gmail.com>
```

WDYT?

**Comment by zhao-kun** [comment]
Sure, I have edited the commit message in your recommendation.

**Comment by grgalex** [comment]
Merged!

**Pull request merged**
